# Generated by Django 4.1 on 2022-10-21 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=60)),
                ('profile_picture', models.ImageField(default='profile_pics/Default.jpg', upload_to='profile_pics')),
                ('comes_from', models.CharField(blank=True, max_length=60, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=60, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('email_visibility', models.CharField(choices=[('False', 'False'), ('True', 'True')], default=('False', 'False'), max_length=6)),
                ('mobile_visibility', models.CharField(choices=[('False', 'False'), ('True', 'True')], default=('False', 'False'), max_length=6)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
