# Generated by Django 4.0.2 on 2022-07-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
