# Generated by Django 4.0.2 on 2022-07-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_author_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
